#include <stdio.h>
#include <kernel/nn.h>
#include <kernel/tty.h>
#include <string.h>

// Symbols generated by objcopy
extern uint8_t _binary_mnist_int8_nn_start[];
extern uint8_t _binary_mnist_int8_nn_end[];

static size_t g_nn_size = 0;

// ----------------------------
// Public API
// ----------------------------
uint8_t* nn_base(void) {
    return NN_BASE_ADDR;
}

size_t nn_size(void) {
    return g_nn_size;
}

nn_header_t* nn_header(void) {
    return (nn_header_t*)NN_BASE_ADDR;
}

// ----------------------------
// Loader
// ----------------------------
int nn_load_embedded(void) {
    uint8_t* src = _binary_mnist_int8_nn_start;
    size_t size = (size_t)(_binary_mnist_int8_nn_end - _binary_mnist_int8_nn_start);

    if (size > NN_MAX_SIZE) {
        printf("NN: model too large (%u bytes)\n", (unsigned)size);
        return -1;
    }

    // Copy model into reserved RAM
    memcpy(NN_BASE_ADDR, src, size);
    g_nn_size = size;

    // Validate header
    nn_header_t* hdr = nn_header();
    if (hdr->magic[0] != 'N' ||
        hdr->magic[1] != 'N' ||
        hdr->magic[2] != 'E' ||
        hdr->magic[3] != 'T') {
        printf("NN: invalid magic\n");
        return -2;
    }

    printf("NN loaded\n");
    printf("  Weights: %u\n", hdr->weight_count);
    printf("  Biases:  %u\n", hdr->bias_count);
    printf("  W scale (Q16.16): %u\n", hdr->weight_scale_q16);
    printf("  B scale (Q16.16): %u\n", hdr->bias_scale_q16);

    return 0;
}

void nn_dump_bytes(size_t count) {
    uint8_t* p = NN_BASE_ADDR;

    printf("NN DUMP (%u bytes):\n", (unsigned)count);

    for (size_t i = 0; i < count; i++) {
        uint8_t b = p[i];

        // Print as two hex digits
        const char hex[] = "0123456789ABCDEF";
        char h1 = hex[(b >> 4) & 0xF];
        char h2 = hex[b & 0xF];

        terminal_putchar(h1);
        terminal_putchar(h2);

        // Separator
        if ((i & 0xF) == 0xF)
            terminal_putchar('\n');   // newline every 16 bytes
        else
            terminal_putchar('.');
    }

    terminal_putchar('\n');
}
